require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DayoffsController do

  # This should return the minimal set of attributes required to create a valid
  # Dayoff. As you add validations to Dayoff, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DayoffsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all dayoffs as @dayoffs" do
      dayoff = Dayoff.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dayoffs).should eq([dayoff])
    end
  end

  describe "GET show" do
    it "assigns the requested dayoff as @dayoff" do
      dayoff = Dayoff.create! valid_attributes
      get :show, {:id => dayoff.to_param}, valid_session
      assigns(:dayoff).should eq(dayoff)
    end
  end

  describe "GET new" do
    it "assigns a new dayoff as @dayoff" do
      get :new, {}, valid_session
      assigns(:dayoff).should be_a_new(Dayoff)
    end
  end

  describe "GET edit" do
    it "assigns the requested dayoff as @dayoff" do
      dayoff = Dayoff.create! valid_attributes
      get :edit, {:id => dayoff.to_param}, valid_session
      assigns(:dayoff).should eq(dayoff)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dayoff" do
        expect {
          post :create, {:dayoff => valid_attributes}, valid_session
        }.to change(Dayoff, :count).by(1)
      end

      it "assigns a newly created dayoff as @dayoff" do
        post :create, {:dayoff => valid_attributes}, valid_session
        assigns(:dayoff).should be_a(Dayoff)
        assigns(:dayoff).should be_persisted
      end

      it "redirects to the created dayoff" do
        post :create, {:dayoff => valid_attributes}, valid_session
        response.should redirect_to(Dayoff.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dayoff as @dayoff" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dayoff.any_instance.stub(:save).and_return(false)
        post :create, {:dayoff => {}}, valid_session
        assigns(:dayoff).should be_a_new(Dayoff)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dayoff.any_instance.stub(:save).and_return(false)
        post :create, {:dayoff => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dayoff" do
        dayoff = Dayoff.create! valid_attributes
        # Assuming there are no other dayoffs in the database, this
        # specifies that the Dayoff created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dayoff.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => dayoff.to_param, :dayoff => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested dayoff as @dayoff" do
        dayoff = Dayoff.create! valid_attributes
        put :update, {:id => dayoff.to_param, :dayoff => valid_attributes}, valid_session
        assigns(:dayoff).should eq(dayoff)
      end

      it "redirects to the dayoff" do
        dayoff = Dayoff.create! valid_attributes
        put :update, {:id => dayoff.to_param, :dayoff => valid_attributes}, valid_session
        response.should redirect_to(dayoff)
      end
    end

    describe "with invalid params" do
      it "assigns the dayoff as @dayoff" do
        dayoff = Dayoff.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dayoff.any_instance.stub(:save).and_return(false)
        put :update, {:id => dayoff.to_param, :dayoff => {}}, valid_session
        assigns(:dayoff).should eq(dayoff)
      end

      it "re-renders the 'edit' template" do
        dayoff = Dayoff.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dayoff.any_instance.stub(:save).and_return(false)
        put :update, {:id => dayoff.to_param, :dayoff => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dayoff" do
      dayoff = Dayoff.create! valid_attributes
      expect {
        delete :destroy, {:id => dayoff.to_param}, valid_session
      }.to change(Dayoff, :count).by(-1)
    end

    it "redirects to the dayoffs list" do
      dayoff = Dayoff.create! valid_attributes
      delete :destroy, {:id => dayoff.to_param}, valid_session
      response.should redirect_to(dayoffs_url)
    end
  end

end
