require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RawdataController do

  # This should return the minimal set of attributes required to create a valid
  # Rawdatum. As you add validations to Rawdatum, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RawdataController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all rawdata as @rawdata" do
      rawdatum = Rawdatum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:rawdata).should eq([rawdatum])
    end
  end

  describe "GET show" do
    it "assigns the requested rawdatum as @rawdatum" do
      rawdatum = Rawdatum.create! valid_attributes
      get :show, {:id => rawdatum.to_param}, valid_session
      assigns(:rawdatum).should eq(rawdatum)
    end
  end

  describe "GET new" do
    it "assigns a new rawdatum as @rawdatum" do
      get :new, {}, valid_session
      assigns(:rawdatum).should be_a_new(Rawdatum)
    end
  end

  describe "GET edit" do
    it "assigns the requested rawdatum as @rawdatum" do
      rawdatum = Rawdatum.create! valid_attributes
      get :edit, {:id => rawdatum.to_param}, valid_session
      assigns(:rawdatum).should eq(rawdatum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Rawdatum" do
        expect {
          post :create, {:rawdatum => valid_attributes}, valid_session
        }.to change(Rawdatum, :count).by(1)
      end

      it "assigns a newly created rawdatum as @rawdatum" do
        post :create, {:rawdatum => valid_attributes}, valid_session
        assigns(:rawdatum).should be_a(Rawdatum)
        assigns(:rawdatum).should be_persisted
      end

      it "redirects to the created rawdatum" do
        post :create, {:rawdatum => valid_attributes}, valid_session
        response.should redirect_to(Rawdatum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rawdatum as @rawdatum" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rawdatum.any_instance.stub(:save).and_return(false)
        post :create, {:rawdatum => {}}, valid_session
        assigns(:rawdatum).should be_a_new(Rawdatum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rawdatum.any_instance.stub(:save).and_return(false)
        post :create, {:rawdatum => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rawdatum" do
        rawdatum = Rawdatum.create! valid_attributes
        # Assuming there are no other rawdata in the database, this
        # specifies that the Rawdatum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Rawdatum.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => rawdatum.to_param, :rawdatum => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested rawdatum as @rawdatum" do
        rawdatum = Rawdatum.create! valid_attributes
        put :update, {:id => rawdatum.to_param, :rawdatum => valid_attributes}, valid_session
        assigns(:rawdatum).should eq(rawdatum)
      end

      it "redirects to the rawdatum" do
        rawdatum = Rawdatum.create! valid_attributes
        put :update, {:id => rawdatum.to_param, :rawdatum => valid_attributes}, valid_session
        response.should redirect_to(rawdatum)
      end
    end

    describe "with invalid params" do
      it "assigns the rawdatum as @rawdatum" do
        rawdatum = Rawdatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rawdatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => rawdatum.to_param, :rawdatum => {}}, valid_session
        assigns(:rawdatum).should eq(rawdatum)
      end

      it "re-renders the 'edit' template" do
        rawdatum = Rawdatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rawdatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => rawdatum.to_param, :rawdatum => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rawdatum" do
      rawdatum = Rawdatum.create! valid_attributes
      expect {
        delete :destroy, {:id => rawdatum.to_param}, valid_session
      }.to change(Rawdatum, :count).by(-1)
    end

    it "redirects to the rawdata list" do
      rawdatum = Rawdatum.create! valid_attributes
      delete :destroy, {:id => rawdatum.to_param}, valid_session
      response.should redirect_to(rawdata_url)
    end
  end

end
